### ISSUE TITLE
Traffic Thread Error: External exception E06D7363

### ISSUE THREAD

**Issue by mungyujeong** [KaAI-KMU/ucwin-can-settings#13]
<img width="703" alt="캡처" src="https://user-images.githubusercontent.com/111988634/229416087-ee50eae0-5e48-4ff7-ba0b-f0d965c5ceaa.PNG">

예제 샘플 코드 중 SampleOverrideCarInput을 사용해 CAN data로 시뮬레이터 차량을 구동 중 알 수 없는 오류가 발생합니다. 
제가 간단하게 만든 도로에서는 문제가 없지만 사측에서 받은 한국맵에서는 다음 사진과 같은 오류가 발생합니다. 
인터넷 검색 및 chatgpt 답변을 듣고 dll 관련 문제 같긴 합니다만 정확히 어떤 것이 문제인지는 모르겠습니다.
일단 제가 사용하는 3rd party library 는 PCAN-Basic API입니다.

**Comment by mungyujeong** [comment]
~~함수에 자동차 인스턴스를 레퍼런스로 전달해서 오류가 났었다.~~
~~레퍼런스를 삭제하니 다른 맵에서도 구동가능했다.~~
같은 오류 계속 발생

**Comment by MoonGyu-Jeong** [comment]
오류를 디버깅하기 위해 MS에서 만든 Windbg 툴을 이용한다.
- https://ikcoo.tistory.com/51
- https://mangsby.com/blog/windows/windbg-c-%EC%98%88%EC%99%B80xe06d7363-%EC%A0%95%EB%B3%B4-%EC%96%BB%EA%B8%B0/

**Comment by mungyujeong** [comment]
CAN data를 UDP로 구현할 것
